version: 2
updates:
  # Python dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    open-pull-requests-limit: 10
    reviewers:
      - "AegisIPC/maintainers"
    labels:
      - "dependencies"
      - "python"
    groups:
      dev-dependencies:
        patterns:
          - "black"
          - "ruff"
          - "mypy"
          - "pytest*"
          - "pre-commit"
        update-types:
          - "minor"
          - "patch"
      security-tools:
        patterns:
          - "bandit"
          - "safety"
          - "pip-audit"
        update-types:
          - "minor"
          - "patch"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    reviewers:
      - "AegisIPC/maintainers"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "ci"
      include: "scope"

  # Docker dependencies
  - package-ecosystem: "docker"
    directory: "/packages/ipc_router"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    reviewers:
      - "AegisIPC/maintainers"
    labels:
      - "dependencies"
      - "docker"
    commit-message:
      prefix: "build"
      include: "scope"