[project]
name = "ipc-cli"
version = "0.1.0"
description = "Command-line interface for AegisIPC framework"
readme = "README.md"
requires-python = ">=3.13"
license = { text = "MIT" }
dependencies = [
    "typer==0.15.1",
    "rich==13.9.4",
    "click==8.1.7",
    "pydantic==2.10.4",
    "ipc-client-sdk==0.1.0",
]

[tool.uv.sources]
ipc-client-sdk = { workspace = true }

[project.scripts]
ipc = "ipc_cli.main:app"

[project.optional-dependencies]
dev = [
    "pytest==8.3.4",
    "pytest-cov==6.0.0",
    "pytest-mock==3.14.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["ipc_cli"]
