[project]
name = "ipc-client-sdk"
version = "0.1.0"
description = "Client SDK for AegisIPC framework"
readme = "README.md"
requires-python = ">=3.13"
license = { text = "MIT" }
dependencies = [
    "nats-py==2.10.0",
    "msgpack==1.1.0",
    "pydantic==2.10.4",
    "asyncio==3.4.3",
]

[project.optional-dependencies]
dev = [
    "pytest==8.3.4",
    "pytest-asyncio==0.25.0",
    "pytest-cov==6.0.0",
    "pytest-mock==3.14.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["ipc_client_sdk"]
